### PR TITLE
`auth` - Fix ODIC authentication failure

### PR DESCRIPTION
**Pull request by ms-zhenhua**
Fix https://github.com/hashicorp/terraform-provider-azurerm/issues/20546

### CODE REVIEW

**Review by tombuildsstuff — APPROVED** [review]
LGTM - thanks for this @ms-zhenhua

**Review by manicminer — APPROVED** [review]
Thanks for the fix @ms-zhenhua 👍

**Comment by adyavanapalli** [comment]
@manicminer or @tombuildsstuff 
This was merged into `main`, but not released. Can someone create a release? GitHub workflows using v3 have this still failing on the OIDC issue.

**Comment by manicminer** [comment]
@adyavanapalli This is included in v0.20230221.1105556 and later and has already been merged into the AzureRM provider. The fix will go out in this week's scheduled provider release.

**Comment by adyavanapalli** [comment]
@manicminer understood. Thanks for the clarification!

**Pull request merged**
