### PR TITLE
add new constant for Azure App Access Panel

### PR DESCRIPTION
**Pull request by gbonk**
I looked for a 'contributors' guide but didn't see anything.  Let me know if this is ok.

### CODE REVIEW

**Comment by gbonk** [comment]
I've signed the "You have signed the CLA for multiple repositories or organizations" and "You have signed the CLA for hashicorp/go-azure-sdk"

Nothing else pops up for me to sign

**Review by manicminer — APPROVED** [review]
Thanks @gbonk, this LGTM 👍 

I'll check on the CLA bot.

**Comment by dlaguerta** [comment]
Hello @gbonk and @manicminer !
I see that the commit is associated with this email:

> From ce225053f834599aeddb6963034f1626a1c26f62 Mon Sep 17 00:00:00 2001
> From: Gregory Bonk <112259176+DevopsMercenary@users.noreply.github.com>
> Date: Mon, 24 Jun 2024 17:21:46 -0400
> Subject: [PATCH] add new constant for Azure App Access Panel

but the email that signed the CLA is `g@bonk.cc`. The CLA checks that the commit authors are in its database, so I believe you'll want to make sure your github user/email is associated with the commit so the bot can give the ✅

**Comment by DevopsMercenary** [comment]
Thank you very much.  I think I got it all signed

**Pull request merged**
